#ifndef OPS_H
#define OPS_H

/**
 * @brief Addressing modes.
 *
 */
typedef enum {
    ADDR_IMPLIED,
    ADDR_IMMEDIATE,
    ADDR_ACCUMULATOR,
    ADDR_RELATIVE,
    ADDR_ABSOLUTE,
    ADDR_ABSOLUTE_X,
    ADDR_ABSOLUTE_Y,
    ADDR_ZERO_PAGE,
    ADDR_ZERO_PAGE_X,
    ADDR_ZERO_PAGE_Y,
    ADDR_INDIRECT, // Special case, only for JMP
    ADDR_INDIRECT_X,
    ADDR_INDIRECT_Y,
} address_mode_t;

/**
 * @brief Operation mnemonics.
 *
 */
typedef enum {
    OP_ADC,
    OP_AND,
    OP_ASL,
    OP_BCC,
    OP_BCS,
    OP_BEQ,
    OP_BIT,
    OP_BMI,
    OP_BNE,
    OP_BPL,
    OP_BRK,
    OP_BVC,
    OP_BVS,
    OP_CLC,
    OP_CLD,
    OP_CLI,
    OP_CLV,
    OP_CMP,
    OP_CPX,
    OP_CPY,
    OP_DEC,
    OP_DEX,
    OP_DEY,
    OP_EOR,
    OP_INC,
    OP_INX,
    OP_INY,
    OP_JMP,
    OP_JSR,
    OP_LDA,
    OP_LDX,
    OP_LDY,
    OP_LSR,
    OP_NOP,
    OP_ORA,
    OP_PHA,
    OP_PHP,
    OP_PLA,
    OP_PLP,
    OP_ROL,
    OP_ROR,
    OP_RTI,
    OP_RTS,
    OP_SBC,
    OP_SEC,
    OP_SED,
    OP_SEI,
    OP_STA,
    OP_STX,
    OP_STY,
    OP_TAX,
    OP_TAY,
    OP_TSX,
    OP_TXA,
    OP_TXS,
    OP_TYA,

    // Invalid opcodes
    OP_ALR,
    OP_ANC,
    OP_ANE,
    OP_ARR,
    OP_DCP,
    OP_ISC,
    OP_LAS,
    OP_LAX,
    OP_LXA,
    OP_RLA,
    OP_RRA,
    OP_SAX,
    OP_SBX,
    OP_SHA,
    OP_SHX,
    OP_SHY,
    OP_SLO,
    OP_SRE,
    OP_TAS,
    OP_JAM,
} mnemonic_t;

/**
 * @brief Operation code structure.
 *
 */
typedef struct {
    /**
     * @brief Operation.
     *
     */
    mnemonic_t mnemonic;

    /**
     * @brief Addressing mode.
     *
     */
    address_mode_t address_mode;
} operation_t;

/**
 * @brief Table of CPU operations.
 *
 */
static const operation_t OP_TABLE[0x100] = {
    {OP_BRK, ADDR_IMPLIED},     {OP_ORA, ADDR_INDIRECT_X},
    {OP_JAM, ADDR_IMPLIED},     {OP_SLO, ADDR_INDIRECT_X},
    {OP_NOP, ADDR_ZERO_PAGE},   {OP_ORA, ADDR_ZERO_PAGE},
    {OP_ASL, ADDR_ZERO_PAGE},   {OP_SLO, ADDR_ZERO_PAGE},
    {OP_PHP, ADDR_IMPLIED},     {OP_ORA, ADDR_IMMEDIATE},
    {OP_ASL, ADDR_ACCUMULATOR}, {OP_ANC, ADDR_IMMEDIATE},
    {OP_NOP, ADDR_ABSOLUTE},    {OP_ORA, ADDR_ABSOLUTE},
    {OP_ASL, ADDR_ABSOLUTE},    {OP_SLO, ADDR_ABSOLUTE},
    {OP_BPL, ADDR_RELATIVE},    {OP_ORA, ADDR_INDIRECT_Y},
    {OP_JAM, ADDR_IMPLIED},     {OP_SLO, ADDR_INDIRECT_Y},
    {OP_NOP, ADDR_ZERO_PAGE_X}, {OP_ORA, ADDR_ZERO_PAGE_X},
    {OP_ASL, ADDR_ZERO_PAGE_X}, {OP_SLO, ADDR_ZERO_PAGE_X},
    {OP_CLC, ADDR_IMPLIED},     {OP_ORA, ADDR_ABSOLUTE_Y},
    {OP_NOP, ADDR_IMPLIED},     {OP_SLO, ADDR_ABSOLUTE_Y},
    {OP_NOP, ADDR_ABSOLUTE_X},  {OP_ORA, ADDR_ABSOLUTE_X},
    {OP_ASL, ADDR_ABSOLUTE_X},  {OP_SLO, ADDR_ABSOLUTE_X},
    {OP_JSR, ADDR_ABSOLUTE},    {OP_AND, ADDR_INDIRECT_X},
    {OP_JAM, ADDR_IMPLIED},     {OP_RLA, ADDR_INDIRECT_X},
    {OP_BIT, ADDR_ZERO_PAGE},   {OP_AND, ADDR_ZERO_PAGE},
    {OP_ROL, ADDR_ZERO_PAGE},   {OP_RLA, ADDR_ZERO_PAGE},
    {OP_PLP, ADDR_IMPLIED},     {OP_AND, ADDR_IMMEDIATE},
    {OP_ROL, ADDR_ACCUMULATOR}, {OP_ANC, ADDR_IMMEDIATE},
    {OP_BIT, ADDR_ABSOLUTE},    {OP_AND, ADDR_ABSOLUTE},
    {OP_ROL, ADDR_ABSOLUTE},    {OP_RLA, ADDR_ABSOLUTE},
    {OP_BMI, ADDR_RELATIVE},    {OP_AND, ADDR_INDIRECT_Y},
    {OP_JAM, ADDR_IMPLIED},     {OP_RLA, ADDR_INDIRECT_Y},
    {OP_NOP, ADDR_ZERO_PAGE_X}, {OP_AND, ADDR_ZERO_PAGE_X},
    {OP_ROL, ADDR_ZERO_PAGE_X}, {OP_RLA, ADDR_ZERO_PAGE_X},
    {OP_SEC, ADDR_IMPLIED},     {OP_AND, ADDR_ABSOLUTE_Y},
    {OP_NOP, ADDR_IMPLIED},     {OP_RLA, ADDR_ABSOLUTE_Y},
    {OP_NOP, ADDR_ABSOLUTE_X},  {OP_AND, ADDR_ABSOLUTE_X},
    {OP_ROL, ADDR_ABSOLUTE_X},  {OP_RLA, ADDR_ABSOLUTE_X},
    {OP_RTI, ADDR_IMPLIED},     {OP_EOR, ADDR_INDIRECT_X},
    {OP_JAM, ADDR_IMPLIED},     {OP_SRE, ADDR_INDIRECT_X},
    {OP_NOP, ADDR_ZERO_PAGE},   {OP_EOR, ADDR_ZERO_PAGE},
    {OP_LSR, ADDR_ZERO_PAGE},   {OP_SRE, ADDR_ZERO_PAGE},
    {OP_PHA, ADDR_IMPLIED},     {OP_EOR, ADDR_IMMEDIATE},
    {OP_LSR, ADDR_ACCUMULATOR}, {OP_ALR, ADDR_IMMEDIATE},
    {OP_JMP, ADDR_ABSOLUTE},    {OP_EOR, ADDR_ABSOLUTE},
    {OP_LSR, ADDR_ABSOLUTE},    {OP_SRE, ADDR_ABSOLUTE},
    {OP_BVC, ADDR_RELATIVE},    {OP_EOR, ADDR_INDIRECT_Y},
    {OP_JAM, ADDR_IMPLIED},     {OP_SRE, ADDR_INDIRECT_Y},
    {OP_NOP, ADDR_ZERO_PAGE_X}, {OP_EOR, ADDR_ZERO_PAGE_X},
    {OP_LSR, ADDR_ZERO_PAGE_X}, {OP_SRE, ADDR_ZERO_PAGE_X},
    {OP_CLI, ADDR_IMPLIED},     {OP_EOR, ADDR_ABSOLUTE_Y},
    {OP_NOP, ADDR_IMPLIED},     {OP_SRE, ADDR_ABSOLUTE_Y},
    {OP_NOP, ADDR_ABSOLUTE_X},  {OP_EOR, ADDR_ABSOLUTE_X},
    {OP_LSR, ADDR_ABSOLUTE_X},  {OP_SRE, ADDR_ABSOLUTE_X},
    {OP_RTS, ADDR_IMPLIED},     {OP_ADC, ADDR_INDIRECT_X},
    {OP_JAM, ADDR_IMPLIED},     {OP_RRA, ADDR_INDIRECT_X},
    {OP_NOP, ADDR_ZERO_PAGE},   {OP_ADC, ADDR_ZERO_PAGE},
    {OP_ROR, ADDR_ZERO_PAGE},   {OP_RRA, ADDR_ZERO_PAGE},
    {OP_PLA, ADDR_IMPLIED},     {OP_ADC, ADDR_IMMEDIATE},
    {OP_ROR, ADDR_ACCUMULATOR}, {OP_ARR, ADDR_IMMEDIATE},
    {OP_JMP, ADDR_INDIRECT},    {OP_ADC, ADDR_ABSOLUTE},
    {OP_ROR, ADDR_ABSOLUTE},    {OP_RRA, ADDR_ABSOLUTE},
    {OP_BVS, ADDR_RELATIVE},    {OP_ADC, ADDR_INDIRECT_Y},
    {OP_JAM, ADDR_IMPLIED},     {OP_RRA, ADDR_INDIRECT_Y},
    {OP_NOP, ADDR_ZERO_PAGE_X}, {OP_ADC, ADDR_ZERO_PAGE_X},
    {OP_ROR, ADDR_ZERO_PAGE_X}, {OP_RRA, ADDR_ZERO_PAGE_X},
    {OP_SEI, ADDR_IMPLIED},     {OP_ADC, ADDR_ABSOLUTE_Y},
    {OP_NOP, ADDR_IMPLIED},     {OP_RRA, ADDR_ABSOLUTE_Y},
    {OP_NOP, ADDR_ABSOLUTE_X},  {OP_ADC, ADDR_ABSOLUTE_X},
    {OP_ROR, ADDR_ABSOLUTE_X},  {OP_RRA, ADDR_ABSOLUTE_X},
    {OP_NOP, ADDR_IMMEDIATE},   {OP_STA, ADDR_INDIRECT_X},
    {OP_NOP, ADDR_IMMEDIATE},   {OP_SAX, ADDR_INDIRECT_X},
    {OP_STY, ADDR_ZERO_PAGE},   {OP_STA, ADDR_ZERO_PAGE},
    {OP_STX, ADDR_ZERO_PAGE},   {OP_SAX, ADDR_ZERO_PAGE},
    {OP_DEY, ADDR_IMPLIED},     {OP_NOP, ADDR_IMMEDIATE},
    {OP_TXA, ADDR_IMPLIED},     {OP_ANE, ADDR_IMMEDIATE},
    {OP_STY, ADDR_ABSOLUTE},    {OP_STA, ADDR_ABSOLUTE},
    {OP_STX, ADDR_ABSOLUTE},    {OP_SAX, ADDR_ABSOLUTE},
    {OP_BCC, ADDR_RELATIVE},    {OP_STA, ADDR_INDIRECT_Y},
    {OP_JAM, ADDR_IMPLIED},     {OP_SHA, ADDR_INDIRECT_Y},
    {OP_STY, ADDR_ZERO_PAGE_X}, {OP_STA, ADDR_ZERO_PAGE_X},
    {OP_STX, ADDR_ZERO_PAGE_Y}, {OP_SAX, ADDR_ZERO_PAGE_Y},
    {OP_TYA, ADDR_IMPLIED},     {OP_STA, ADDR_ABSOLUTE_Y},
    {OP_TXS, ADDR_IMPLIED},     {OP_TAS, ADDR_ABSOLUTE_Y},
    {OP_SHY, ADDR_ABSOLUTE_X},  {OP_STA, ADDR_ABSOLUTE_X},
    {OP_SHX, ADDR_ABSOLUTE_Y},  {OP_SHA, ADDR_ABSOLUTE_Y},
    {OP_LDY, ADDR_IMMEDIATE},   {OP_LDA, ADDR_INDIRECT_X},
    {OP_LDX, ADDR_IMMEDIATE},   {OP_LAX, ADDR_INDIRECT_X},
    {OP_LDY, ADDR_ZERO_PAGE},   {OP_LDA, ADDR_ZERO_PAGE},
    {OP_LDX, ADDR_ZERO_PAGE},   {OP_LAX, ADDR_ZERO_PAGE},
    {OP_TAY, ADDR_IMPLIED},     {OP_LDA, ADDR_IMMEDIATE},
    {OP_TAX, ADDR_IMPLIED},     {OP_LXA, ADDR_IMMEDIATE},
    {OP_LDY, ADDR_ABSOLUTE},    {OP_LDA, ADDR_ABSOLUTE},
    {OP_LDX, ADDR_ABSOLUTE},    {OP_LAX, ADDR_ABSOLUTE},
    {OP_BCS, ADDR_RELATIVE},    {OP_LDA, ADDR_INDIRECT_Y},
    {OP_JAM, ADDR_IMPLIED},     {OP_LAX, ADDR_INDIRECT_Y},
    {OP_LDY, ADDR_ZERO_PAGE_X}, {OP_LDA, ADDR_ZERO_PAGE_X},
    {OP_LDX, ADDR_ZERO_PAGE_Y}, {OP_LAX, ADDR_ZERO_PAGE_Y},
    {OP_CLV, ADDR_IMPLIED},     {OP_LDA, ADDR_ABSOLUTE_Y},
    {OP_TSX, ADDR_IMPLIED},     {OP_LAS, ADDR_ABSOLUTE_Y},
    {OP_LDY, ADDR_ABSOLUTE_X},  {OP_LDA, ADDR_ABSOLUTE_X},
    {OP_LDX, ADDR_ABSOLUTE_Y},  {OP_LAX, ADDR_ABSOLUTE_Y},
    {OP_CPY, ADDR_IMMEDIATE},   {OP_CMP, ADDR_INDIRECT_X},
    {OP_NOP, ADDR_IMMEDIATE},   {OP_DCP, ADDR_INDIRECT_X},
    {OP_CPY, ADDR_ZERO_PAGE},   {OP_CMP, ADDR_ZERO_PAGE},
    {OP_DEC, ADDR_ZERO_PAGE},   {OP_DCP, ADDR_ZERO_PAGE},
    {OP_INY, ADDR_IMPLIED},     {OP_CMP, ADDR_IMMEDIATE},
    {OP_DEX, ADDR_IMPLIED},     {OP_SBX, ADDR_IMMEDIATE},
    {OP_CPY, ADDR_ABSOLUTE},    {OP_CMP, ADDR_ABSOLUTE},
    {OP_DEC, ADDR_ABSOLUTE},    {OP_DCP, ADDR_ABSOLUTE},
    {OP_BNE, ADDR_RELATIVE},    {OP_CMP, ADDR_INDIRECT_Y},
    {OP_JAM, ADDR_IMPLIED},     {OP_DCP, ADDR_INDIRECT_Y},
    {OP_NOP, ADDR_ZERO_PAGE_X}, {OP_CMP, ADDR_ZERO_PAGE_X},
    {OP_DEC, ADDR_ZERO_PAGE_X}, {OP_DCP, ADDR_ZERO_PAGE_X},
    {OP_CLD, ADDR_IMPLIED},     {OP_CMP, ADDR_ABSOLUTE_Y},
    {OP_NOP, ADDR_IMPLIED},     {OP_DCP, ADDR_ABSOLUTE_Y},
    {OP_NOP, ADDR_ABSOLUTE_X},  {OP_CMP, ADDR_ABSOLUTE_X},
    {OP_DEC, ADDR_ABSOLUTE_X},  {OP_DCP, ADDR_ABSOLUTE_X},
    {OP_CPX, ADDR_IMMEDIATE},   {OP_SBC, ADDR_INDIRECT_X},
    {OP_NOP, ADDR_IMMEDIATE},   {OP_ISC, ADDR_INDIRECT_X},
    {OP_CPX, ADDR_ZERO_PAGE},   {OP_SBC, ADDR_ZERO_PAGE},
    {OP_INC, ADDR_ZERO_PAGE},   {OP_ISC, ADDR_ZERO_PAGE},
    {OP_INX, ADDR_IMPLIED},     {OP_SBC, ADDR_IMMEDIATE},
    {OP_NOP, ADDR_IMPLIED},     {OP_SBC, ADDR_IMMEDIATE},
    {OP_CPX, ADDR_ABSOLUTE},    {OP_SBC, ADDR_ABSOLUTE},
    {OP_INC, ADDR_ABSOLUTE},    {OP_ISC, ADDR_ABSOLUTE},
    {OP_BEQ, ADDR_RELATIVE},    {OP_SBC, ADDR_INDIRECT_Y},
    {OP_JAM, ADDR_IMPLIED},     {OP_ISC, ADDR_INDIRECT_Y},
    {OP_NOP, ADDR_ZERO_PAGE_X}, {OP_SBC, ADDR_ZERO_PAGE_X},
    {OP_INC, ADDR_ZERO_PAGE_X}, {OP_ISC, ADDR_ZERO_PAGE_X},
    {OP_SED, ADDR_IMPLIED},     {OP_SBC, ADDR_ABSOLUTE_Y},
    {OP_NOP, ADDR_IMPLIED},     {OP_ISC, ADDR_ABSOLUTE_Y},
    {OP_NOP, ADDR_ABSOLUTE_X},  {OP_SBC, ADDR_ABSOLUTE_X},
    {OP_INC, ADDR_ABSOLUTE_X},  {OP_ISC, ADDR_ABSOLUTE_X},
};

/**
 * @brief Size of an op + operand by address mode.
 *
 * This will determine the program counter increment.
 *
 */
static const unsigned char ADDRESS_MODE_SIZES[13] = {
    1, // ADDR_IMPLIED
    2, // ADDR_IMMEDIATE
    1, // ADDR_ACCUMULATOR
    2, // ADDR_RELATIVE
    3, // ADDR_ABSOLUTE
    3, // ADDR_ABSOLUTE_X
    3, // ADDR_ABSOLUTE_Y
    2, // ADDR_ZERO_PAGE
    2, // ADDR_ZERO_PAGE_X
    2, // ADDR_ZERO_PAGE_Y
    3, // ADDR_INDIRECT
    2, // ADDR_INDIRECT_X
    2, // ADDR_INDIRECT_Y
};

#endif